using System;
using System.Buffers.Binary;
using System.IO;
using System.Security.Cryptography;
using System.Text;

namespace UvfLib.Core.Common
{
    /// <summary>
    /// EC (P-384) key material and ECDH-ES key agreement for public-key vault recipients.
    /// <para>
    /// Wrapping a vault CEK to a user's public key uses ECDH-ES+A256KW (RFC 7518 §4.6): an ephemeral
    /// EC key agrees a shared secret Z with the recipient's static key, a 256-bit key-encryption key
    /// (KEK) is derived from Z with the Concat KDF (NIST SP 800-56A; a single SHA-256 block suffices
    /// for a 256-bit key), and the CEK is AES-KeyWrapped (RFC 3394) under that KEK.
    /// </para>
    /// <para>
    /// Private keys are exported as password-encrypted PKCS#8 (AES-256-CBC); public keys as
    /// SubjectPublicKeyInfo. Both are standard, AOT-safe .NET crypto APIs.
    /// </para>
    /// </summary>
    public static class EcdhKeyMaterial
    {
        /// <summary>The curve used for user key pairs.</summary>
        public const string CurveName = "P-384";

        /// <summary>Generates a fresh P-384 key pair for a user.</summary>
        public static ECDiffieHellman GenerateKeyPair() => ECDiffieHellman.Create(ECCurve.NamedCurves.nistP384);

        /// <summary>Exports the public key as SubjectPublicKeyInfo (DER).</summary>
        public static byte[] ExportPublicKey(ECDiffieHellman key) => key.ExportSubjectPublicKeyInfo();

        /// <summary>Imports a SubjectPublicKeyInfo (DER) public key. The returned instance must be disposed.</summary>
        public static ECDiffieHellman ImportPublicKey(byte[] subjectPublicKeyInfo)
        {
            var ecdh = ECDiffieHellman.Create();
            ecdh.ImportSubjectPublicKeyInfo(subjectPublicKeyInfo, out _);
            return ecdh;
        }

        // Private keys are wrapped with a PORTABLE scheme — PBKDF2-HMAC-SHA256 -> AES-256-GCM over the
        // plain PKCS#8 bytes — rather than the platform's encrypted-PKCS#8 (PBES2). The platform PBES2
        // path is NOT reliable across runtimes/AOT targets: a blob exported on Windows (CNG) fails to
        // import on Linux/macOS (OpenSSL) with "EncryptedPrivateKeyInfo ... password may be incorrect".
        // AES-GCM + PBKDF2 are the same primitives the vault content layer uses, so they round-trip on
        // every platform. Container: magic(5) || salt(16) || nonce(12) || tag(16) || ciphertext.
        private static readonly byte[] KeyWrapMagic = { (byte)'U', (byte)'V', (byte)'F', (byte)'K', 0x01 };
        private const int WrapSaltLen = 16, WrapNonceLen = 12, WrapTagLen = 16, WrapKeyLen = 32, WrapIterations = 210_000;

        /// <summary>Exports the private key as a password-wrapped blob (PBKDF2-SHA256 → AES-256-GCM over plain PKCS#8).</summary>
        public static byte[] ExportEncryptedPrivateKey(ECDiffieHellman key, char[] password)
        {
            byte[] pkcs8 = key.ExportPkcs8PrivateKey();
            byte[] pw = Encoding.UTF8.GetBytes(password);
            byte[] salt = RandomNumberGenerator.GetBytes(WrapSaltLen);
            byte[] nonce = RandomNumberGenerator.GetBytes(WrapNonceLen);
            byte[]? dek = null;
            try
            {
                dek = Rfc2898DeriveBytes.Pbkdf2(pw, salt, WrapIterations, HashAlgorithmName.SHA256, WrapKeyLen);
                byte[] cipher = new byte[pkcs8.Length];
                byte[] tag = new byte[WrapTagLen];
                using (var gcm = new AesGcm(dek, WrapTagLen))
                {
                    gcm.Encrypt(nonce, pkcs8, cipher, tag);
                }
                byte[] outBuf = new byte[KeyWrapMagic.Length + WrapSaltLen + WrapNonceLen + WrapTagLen + cipher.Length];
                int o = 0;
                Buffer.BlockCopy(KeyWrapMagic, 0, outBuf, o, KeyWrapMagic.Length); o += KeyWrapMagic.Length;
                Buffer.BlockCopy(salt, 0, outBuf, o, WrapSaltLen); o += WrapSaltLen;
                Buffer.BlockCopy(nonce, 0, outBuf, o, WrapNonceLen); o += WrapNonceLen;
                Buffer.BlockCopy(tag, 0, outBuf, o, WrapTagLen); o += WrapTagLen;
                Buffer.BlockCopy(cipher, 0, outBuf, o, cipher.Length);
                return outBuf;
            }
            finally
            {
                CryptographicOperations.ZeroMemory(pkcs8);
                CryptographicOperations.ZeroMemory(pw);
                if (dek != null) CryptographicOperations.ZeroMemory(dek);
            }
        }

        /// <summary>Imports a private key wrapped by <see cref="ExportEncryptedPrivateKey"/> (legacy encrypted-PKCS#8 blobs are still accepted as a fallback). The returned instance must be disposed.</summary>
        public static ECDiffieHellman ImportEncryptedPrivateKey(byte[] encrypted, char[] password)
        {
            // Legacy blobs (platform encrypted-PKCS#8, pre-fix) don't carry our magic — fall back to the
            // old import so keys generated by an earlier build still load (works on Windows).
            if (encrypted.Length < KeyWrapMagic.Length ||
                !encrypted.AsSpan(0, KeyWrapMagic.Length).SequenceEqual(KeyWrapMagic))
            {
                var legacy = ECDiffieHellman.Create();
                legacy.ImportEncryptedPkcs8PrivateKey(password, encrypted, out _);
                return legacy;
            }

            int o = KeyWrapMagic.Length;
            byte[] salt = encrypted[o..(o + WrapSaltLen)]; o += WrapSaltLen;
            byte[] nonce = encrypted[o..(o + WrapNonceLen)]; o += WrapNonceLen;
            byte[] tag = encrypted[o..(o + WrapTagLen)]; o += WrapTagLen;
            byte[] cipher = encrypted[o..];
            byte[] pw = Encoding.UTF8.GetBytes(password);
            byte[] pkcs8 = new byte[cipher.Length];
            byte[]? dek = null;
            try
            {
                dek = Rfc2898DeriveBytes.Pbkdf2(pw, salt, WrapIterations, HashAlgorithmName.SHA256, WrapKeyLen);
                using (var gcm = new AesGcm(dek, WrapTagLen))
                {
                    gcm.Decrypt(nonce, cipher, tag, pkcs8);
                }
                var ecdh = ECDiffieHellman.Create();
                ecdh.ImportPkcs8PrivateKey(pkcs8, out _);
                return ecdh;
            }
            finally
            {
                CryptographicOperations.ZeroMemory(pkcs8);
                CryptographicOperations.ZeroMemory(pw);
                if (dek != null) CryptographicOperations.ZeroMemory(dek);
            }
        }

        /// <summary>
        /// Derives the 256-bit KEK for ECDH-ES+A256KW:
        /// SHA-256( 0x00000001 || Z || OtherInfo ), where
        /// OtherInfo = AlgorithmID("A256KW") || PartyUInfo() || PartyVInfo() || SuppPubInfo(256).
        /// Empty apu/apv. .NET's DeriveKeyFromHash computes hash(prepend || Z || append) over the
        /// agreed secret Z, which equals the single-block Concat KDF output.
        /// </summary>
        public static byte[] DeriveKek(ECDiffieHellman ourKey, ECDiffieHellmanPublicKey otherPublicKey)
        {
            byte[] prepend = new byte[4];
            BinaryPrimitives.WriteUInt32BigEndian(prepend, 1u); // Concat KDF counter = 1
            byte[] otherInfo = BuildOtherInfo("A256KW", 256);
            return ourKey.DeriveKeyFromHash(otherPublicKey, HashAlgorithmName.SHA256, prepend, otherInfo);
        }

        private static byte[] BuildOtherInfo(string algorithmId, int keyDataLenBits)
        {
            using var ms = new MemoryStream();
            WriteLengthPrefixed(ms, Encoding.ASCII.GetBytes(algorithmId)); // AlgorithmID
            WriteLengthPrefixed(ms, Array.Empty<byte>());                  // PartyUInfo (apu) — empty
            WriteLengthPrefixed(ms, Array.Empty<byte>());                  // PartyVInfo (apv) — empty
            byte[] supp = new byte[4];
            BinaryPrimitives.WriteUInt32BigEndian(supp, (uint)keyDataLenBits); // SuppPubInfo = keydatalen
            ms.Write(supp, 0, 4);
            return ms.ToArray();
        }

        private static void WriteLengthPrefixed(MemoryStream ms, byte[] data)
        {
            byte[] len = new byte[4];
            BinaryPrimitives.WriteUInt32BigEndian(len, (uint)data.Length);
            ms.Write(len, 0, 4);
            if (data.Length > 0) ms.Write(data, 0, data.Length);
        }
    }
}
